const data = {
  products: [
    {
      _id: '1',
      name: 'Harry Potter',
      slug: 'harry-potter',
      category: 'Children',
      image: '/images/p1.jpeg',
      price: 49,
      countInStock: 10,
      brand: 'Arthur',
      rating: 4.5,
      numReviews: 10,
      description: 'SF',
    },
    {
      _id: '2',
      name: 'Warriors',
      slug: 'warriors',
      category: 'Children',
      image: '/images/p2.jpeg',
      price: 35,
      countInStock: 20,
      brand: 'Arthur',
      rating: 4.0,
      numReviews: 10,
      description: 'SF',
    },
    {
      _id: '3',
      name: 'The Little Prince',
      slug: 'the-little-prince',
      category: 'Children',
      image: '/images/p3.jpeg',
      price: 25,
      countInStock: 15,
      brand: 'Corint',
      rating: 4.5,
      numReviews: 14,
      description: 'story aboit life',
    },
    {
      _id: '4',
      name: 'Pride and Prejudice',
      slug: 'pride-and-prejudice',
      category: 'Romance',
      image: '/images/p4.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'Corint',
      rating: 4.5,
      numReviews: 10,
      description: 'love story',
    },
    {
      _id: '5',
      name: 'The Love Hypothesis',
      slug: 'the-love-hypothesis',
      category: 'Romance',
      image: '/images/p5.jpeg',
      price: 65,
      countInStock: 5,
      brand: 'Corint',
      rating: 4.5,
      numReviews: 10,
      description: 'love story',
    },
    {
      _id: '6',
      name: 'Jane Eyre',
      slug: 'jane-eyre',
      category: 'Romance',
      image: '/images/p6.jpeg',
      price: 25,
      countInStock: 5,
      brand: 'Corint',
      rating: 4.5,
      numReviews: 10,
      description: 'love story',
    },
  ],
};
export default data;
